// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4EbIGbo6Wo5PomsOqyEprk1TH7zuB1cM',
    appId: '1:279165111660:web:8c788faecc225e56b6b749',
    messagingSenderId: '279165111660',
    projectId: 'familyfridgefinal',
    authDomain: 'familyfridgefinal.firebaseapp.com',
    storageBucket: 'familyfridgefinal.appspot.com',
    measurementId: 'G-TGBDJ0WNJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBfhCGjvPqloMkt6gxjq2MB_DfzGFkvFI',
    appId: '1:279165111660:android:ca15ff85a22c5a44b6b749',
    messagingSenderId: '279165111660',
    projectId: 'familyfridgefinal',
    storageBucket: 'familyfridgefinal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFRsvdgAvcFRnJZbX0VLmGu5AH8sl5IiY',
    appId: '1:279165111660:ios:64d5f4e9fbff8e56b6b749',
    messagingSenderId: '279165111660',
    projectId: 'familyfridgefinal',
    storageBucket: 'familyfridgefinal.appspot.com',
    androidClientId: '279165111660-b59ellgt5q6nva1rg9hg9tvobnr532pf.apps.googleusercontent.com',
    iosClientId: '279165111660-tmk4ruit187hpk0fpr1qnm0mhlno73o3.apps.googleusercontent.com',
    iosBundleId: 'com.example.familyfridgefinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFRsvdgAvcFRnJZbX0VLmGu5AH8sl5IiY',
    appId: '1:279165111660:ios:1604ffb8b17d0665b6b749',
    messagingSenderId: '279165111660',
    projectId: 'familyfridgefinal',
    storageBucket: 'familyfridgefinal.appspot.com',
    androidClientId: '279165111660-b59ellgt5q6nva1rg9hg9tvobnr532pf.apps.googleusercontent.com',
    iosClientId: '279165111660-cl0rre9o149dn7eslf2hbfc33aub40bd.apps.googleusercontent.com',
    iosBundleId: 'com.example.familyfridgefinal.RunnerTests',
  );
}
